feat(documentation_website): Automated deployment
awslabs/generative-ai-cdk-constructs pull request #281
Opened 2024-02-22 00:29 UTC by MichaelWalker-git

### Description
- Automated Github actions for building the documentation website.

2024-02-26 18:49 UTC, krokoko commented
could you also add the website folder to project.npmignore?.addPatterns() please ?

2024-02-26 19:10 UTC, scottschreckengaust requested changes
tests failing lets investigate first

2024-02-27 16:48 UTC, MichaelWalker-git commented
It looks like the commit link is from the bot?

2024-02-27 21:37 UTC, krokoko approved these changes

2024-02-29 18:23 UTC, dineshSajwan approved these changes

2024-02-29 18:23 UTC, merged