feat(bedrock): New embedding model config
awslabs/generative-ai-cdk-constructs pull request #665
Opened 2024-08-27 18:21 UTC by aws-rafams

Fixes #657

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the project license.

2024-08-27 19:49 UTC, krokoko commented on test/cdk-lib/bedrock/integ-tests/kb.integ.ts
> +// const apiCall =
we should remove or implement the commented code

2024-08-27 19:54 UTC, krokoko submitted a review, later dismissed

2024-08-27 19:58 UTC, krokoko commented
Failing build

2024-08-27 20:02 UTC, aws-rafams commented
> Failing build



> Failing build

I see it fails because of an assert on the integ test snapshot. Same reason why I had to comment out part of the code. Will look into it.

2024-08-27 21:20 UTC, aws-rafams commented
seems the assert fails due to some non-deterministic operation and my local build succeeds due to some local caching, will continue to look into a possible solution

2024-08-29 17:05 UTC, krokoko requested changes
Waiting for https://github.com/awslabs/generative-ai-cdk-constructs/pull/663 to go in before merging this

2024-09-04 18:31 UTC, krokoko approved these changes

2024-09-04 18:39 UTC, scottschreckengaust approved these changes
LGTM

2024-09-04 18:40 UTC, merged