feat(construct): update model id in aws-contentgen-appsync-lambda construct.
awslabs/generative-ai-cdk-constructs pull request #722
Opened 2024-10-01 19:27 UTC by dineshSajwan

Fixes #
Fix bug and update model id in aws-contentgen-appsync-lambda.
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the project license.

2024-10-04 16:28 UTC, krokoko commented on lambda/aws-contentgen-appsync-lambda/src/util.py
> +from enum import StrEnum
license header

2024-10-04 16:30 UTC, krokoko requested changes
LGTM, main points:
- missing license header
- buid failed on mutation
Once fixed will approve :)

2024-10-04 18:56 UTC, scottschreckengaust commented on lambda/aws-contentgen-appsync-lambda/src/image_generator.py
> -    @tracer.capture_method
I'm curious if the `@tracer` decorators need to be removed.

2024-10-04 19:23 UTC, krokoko approved these changes

2024-10-07 16:05 UTC, scottschreckengaust approved these changes

2024-10-07 16:06 UTC, merged